config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'cd_products#index'
  get '/guide' => 'users#guide'
 namespace :admin do
    resources :commodities, :only =>[:new,:create,:index,:edite,:update,:destroy]
    resources :companeys, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :doramas, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :movies, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :companeys, :only =>[:new,:create,:edit,:update,:destroy]
    resources :companeys, :only =>[:edit,:update]
    resources :users, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :artists, :only =>[:new,:create,:index,:edit,:update,:destroy]
  end
   get '/trend' =>'cms#trend'
 resources :cms, :only => [:index,:search]
  get '/era_search' => 'cd_products#era_search'
  get '/release_era_tag/:id' => 'release_era_tags#show', as: 'release_era_tag'
  get '/cd_products/:id' => 'cd_products#show'
  get '/search/list' => 'cd_products#list', as: :search_list
  get '/doramas/title_search/:id/:dorama_name' => "doramas#title_search", as: :dorama_title_search
  get '/doramas/feature' => 'doramas#feature', as: 'doramas_feature'
  get '/movies/title_search/:id/:movie_name' => "movies#title_search", as: :movie_title_search
  get '/movies/feature' => "movies#feature", as: :movie_feature
  get '/cms/commodity_search' => "cms#commodity_search", as: :cm_commodity_search
  get '/cms/company_search' => "cms#company_search", as: :cm_company_search
  get '/cd_products/search/artists_search_form' => "cd_products#artists_search_form", as: :artists_search_form
  get '/cd_products/search/songs_search_form' => "cd_products#songs_search_form", as: :songs_search_form
  get '/cd_products/search/artists_search' => "cd_products#artists_search", as: :artists_search
  get '/cd_products/search/songs_search' => "cd_products#songs_search", as: :songs_search
  resources :cd_products do
    post 'add' => 'favorites#create'
    delete '/add' => 'favorites#destroy'
  end
  resources :cd_products, :only =>[:index,:show,:era_search,:era_search_list,:search,:list]
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    password: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  devise_scope :user do
 post 'users/sign_up/confirm' => 'users/registrations#confirm'
 post 'users/sign_up/complete' => 'users/registrations#complete'
end

  resources :commodities, :only =>[:new,:create,:index,:edite,:update,:destroy]
  resources :companeys, :only =>[:new,:create,:index,:edit,:update,:destroy]
  resources :doramas, :only => [:new,:create,:index,:edit,:update,:destroy]
  resources :movies, :only =>[:new,:create,:index,:edit,:update,:destroy]
  resources :admins
  resources :bag_items, :only =>[:index,:edit,:update,:destroy]
  resources :shopping_bags, :only =>[:new,:create,:index,:show,:destroy]
  resources :cart_items, :only =>[:create,:destroy,:update]
  resources :shopping_carts, :only => [:new,:create,:index,:show,:destroy]
  get '/confirmation' => "shopping_carts#purchase"
  post  '/complete' => "shopping_carts#complete"
  resources :address_lines, :only =>[:new,:create,:index,:edit,:update,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/resignnation'
  get 'users/complete'
  resources :users,:except =>[:new,:create,:destroy]

end

app/controllers/cms_controller.rb
class CmsController < ApplicationController

include Search

  def index
  	@cd_products = CdProduct.where("commodity_id not ?", nil).where(sale_status_id: 2).order(release_date: :desc).page(params[:page]).per(9)
  end

  def trend
   @cd_products = CdProduct.where("commodity_id not ?", nil).where(sale_status_id: 2).order(release_date: :desc).limit(9)
  end

  def commodity_search
     search_name = params[:search_name]
   if search_name == ""
     return redirect_to cms_path
   end
     @commodities = commodity_name_search_function(search_name)
   @match_records = CdProduct.where(commodity_id:@commodities.ids).where(sale_status_id: 2).count
   @commodities_cd_products = CdProduct.where(commodity_id:@commodities.ids).where(sale_status_id: 2).page(params[:page]).per(12)
   @path = controller_path + '#' + action_name
   def @path.is(*str)
       str.map{|s| self.include?(s)}.include?(true)
   end
     render template: "cd_products/list"
 end

 def company_search
   search_name = params[:search_name]
   if search_name == ""
     return redirect_to cms_path
   end
   @companies = company_name_search_function(search_name)
   @companies_commodities = Commodity.where(company_id:@companies.ids)
   @match_records = CdProduct.where(commodity_id:@companies_commodities.ids).where(sale_status_id: 2).count
   @companies_cd_products = CdProduct.where(commodity_id:@companies_commodities.ids).where(sale_status_id: 2).page(params[:page]).per(12)
   @path = controller_path + '#' + action_name
   def @path.is(*str)
       str.map{|s| self.include?(s)}.include?(true)
   end
   render template: "cd_products/list"
 end

end

app/helpers/cms_helper.rb
module CmsHelper
end

app/views/cms/_commodity_name_search.html.erb
<%=form_tag(cm_commodity_search_path, method: :get) do %>
	<%= label_tag "商品名検索" %>
	<%= text_field_tag :search_name %>
	<%= submit_tag "検索" %>
<% end %>

app/views/cms/_company_name_search.html.erb
<%=form_tag(cm_company_search_path, method: :get) do %>
	<%= label_tag "会社名検索" %>
	<%= text_field_tag :search_name %>
	<%= submit_tag "検索" %>
<% end %>

app/views/cms/_goods_name_search.html.erb
<%=form_tag(cm_goods_search_path, method: :get) do %>
	<%= label_tag "商品名検索" %>
	<%= text_field_tag :search_name %>
	<%= submit_tag "検索" %>
<% end %>

app/views/cms/index.html.erb
<html>
<head>
</head>
<body>
	<%= render partial: 'cd_products/header' %>
  <div class="main clearfix">
	<div class="main-content">
		<!-- 商品名検索 -->
		<%= render partial: 'cms/commodity_name_search' %>
		<!-- 会社名検索 -->
		<%= render partial: 'cms/company_name_search' %>
		<!-- タイトル部分 -->
		<div class="jumbotron" style="background-image: url(/assets/cm_top.jpeg);background-size: cover;">
			<h1 style="color:white">CM音楽トップ</h1>
			<p style="color:white"><%= link_to "最新CM情報はコチラ", trend_path %></p>
		</div>
		<!-- CMCD一覧 -->
		<h3>CM音楽CD一覧</h3>
		<% if@cd_products.present? %>
			<% @cd_products.each_with_index do |cd_product, i| %>
				<div class="col-xs-4">
					<% if cd_product.jacket_image.present? %>
						<%= link_to cd_product_path(cd_product.id) do %>
							<%= image_tag "#{cd_product.jacket_image}", :size =>'250x250' %>
						<% end %>
					<% else %>
						<%= link_to cd_product_path(cd_product.id) do %>
							<img src="/assets/no_image.jpg", width="250", height="250">
						<% end %>
					<% end %>
					<p>CD名：<%= cd_product.name %></p>
					<p>アーティスト名：<%= cd_product.artist.name %></p>
					<p>リリース日：<%= cd_product.release_date %></p>
					<p>商品名：<%= cd_product.commodity.commodity %></p>
					<p>会社名：<%= cd_product.commodity.company.company %></p>
				</div>
			<% end %>
		<% end %>
		<div class="col-xs-12"><%= paginate @cd_products %></div class="col-xs-12">
	</div>
	<%= render partial: 'cd_products/sidebar' %>
  </div>
  <%= render partial: 'cd_products/footer' %>
</body>
</html>

app/views/cms/search.html.erb
<h1>Cms#search</h1>
<p>Find me in app/views/cms/search.html.erb</p>

app/views/cms/trend.html.erb
<%= render partial: 'cd_products/header' %>
  <div class="main clearfix">
    <div class="main-content">
        <div class="container">
            <h3>最新CM音楽CD</h3>
                <% if@cd_products.present? %>
            <% @cd_products.each_with_index do |cd_product, id| %>
                        <div class="col-xs-5">
                            <% if cd_product.jacket_image.present? %>
                                <%= link_to cd_product_path(cd_product.id) do %>
                                    <%= image_tag "#{cd_product.jacket_image}", :size =>'250x250' %>
                                <% end %>
                            <% else %>
                                <%= link_to cd_product_path(cd_product.id) do %>
                                <img src="/assets/no_image.jpg", width="250", height="250">
                                 <% end %>
                            <% end %>
                            <p>CD名：<%= cd_product.name %></p>
                            <p>アーティスト名：<%= cd_product.artist.name %></p>
                            <p>リリース日：<%= cd_product.release_date %></p>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="<%= "#cm#{id}" %>">CMを見る</button>
                     <div class="modal fade" id="<%= "cm#{id}" %>" tabindex="-1">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal"><span>×</span></button>
                                            <h4 class="modal-title">CM商品名：<%= cd_product.commodity.commodity %>公開日：<%= cd_product.commodity.upload_date %></h4>
                                        </div>
                                        <div class="modal-body">
                                            <iframe width="500" height="300" src=<%= cd_product.commodity.video_url %> frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                <% end %>
            <% end %>
         </div>
    </div>
    <%= render partial: 'cd_products/sidebar' %>
  </div>
  <%= render partial: 'cd_products/footer' %>