config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'cd_products#index'
  get '/guide' => 'users#guide'
 namespace :admin do
    resources :commodities, :only =>[:new,:create,:index,:edite,:update,:destroy]
    resources :companeys, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :doramas, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :movies, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :companeys, :only =>[:new,:create,:edit,:update,:destroy]
    resources :companeys, :only =>[:edit,:update]
    resources :users, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :artists, :only =>[:new,:create,:index,:edit,:update,:destroy]
  end
   get '/trend' =>'cms#trend'
 resources :cms, :only => [:index,:search]
  get '/era_search' => 'cd_products#era_search'
  get '/release_era_tag/:id' => 'release_era_tags#show', as: 'release_era_tag'
  get '/cd_products/:id' => 'cd_products#show'
  get '/search/list' => 'cd_products#list', as: :search_list
  get '/doramas/title_search/:id/:dorama_name' => "doramas#title_search", as: :dorama_title_search
  get '/doramas/feature' => 'doramas#feature', as: 'doramas_feature'
  get '/movies/title_search/:id/:movie_name' => "movies#title_search", as: :movie_title_search
  get '/movies/feature' => "movies#feature", as: :movie_feature
  get '/cms/commodity_search' => "cms#commodity_search", as: :cm_commodity_search
  get '/cms/company_search' => "cms#company_search", as: :cm_company_search
  get '/cd_products/search/artists_search_form' => "cd_products#artists_search_form", as: :artists_search_form
  get '/cd_products/search/songs_search_form' => "cd_products#songs_search_form", as: :songs_search_form
  get '/cd_products/search/artists_search' => "cd_products#artists_search", as: :artists_search
  get '/cd_products/search/songs_search' => "cd_products#songs_search", as: :songs_search
  resources :cd_products do
    post 'add' => 'favorites#create'
    delete '/add' => 'favorites#destroy'
  end
  resources :cd_products, :only =>[:index,:show,:era_search,:era_search_list,:search,:list]
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    password: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  devise_scope :user do
 post 'users/sign_up/confirm' => 'users/registrations#confirm'
 post 'users/sign_up/complete' => 'users/registrations#complete'
end

  resources :commodities, :only =>[:new,:create,:index,:edite,:update,:destroy]
  resources :companeys, :only =>[:new,:create,:index,:edit,:update,:destroy]
  resources :doramas, :only => [:new,:create,:index,:edit,:update,:destroy]
  resources :movies, :only =>[:new,:create,:index,:edit,:update,:destroy]
  resources :admins
  resources :bag_items, :only =>[:index,:edit,:update,:destroy]
  resources :shopping_bags, :only =>[:new,:create,:index,:show,:destroy]
  resources :cart_items, :only =>[:create,:destroy,:update]
  resources :shopping_carts, :only => [:new,:create,:index,:show,:destroy]
  get '/confirmation' => "shopping_carts#purchase"
  post  '/complete' => "shopping_carts#complete"
  resources :address_lines, :only =>[:new,:create,:index,:edit,:update,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/resignnation'
  get 'users/complete'
  resources :users,:except =>[:new,:create,:destroy]

end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
	has_many :cart_items, dependent: :destroy
	belongs_to :user

	def sum_total_price
		cart_items.to_a.sum { |cart_item| cart_item.total_price }
	end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController

  	def show
	  	@shopping_cart = current_user.shopping_cart
	  	@cart_items = current_user.shopping_cart.cart_items
	  	@address_lines = current_user.address_lines
  	end

  	def purchase
  		@shopping_cart = current_user.shopping_cart
  		@shopping_cart_id = current_user.shopping_cart.id
 	  	@cart_items = current_user.shopping_cart.cart_items
 	  	@address_line = AddressLine.find(params[:address_line][:address_line_id])
 	  	@address_line_id = @address_line.id
  	end
  	def complete
  		shopping_bag = ShoppingBag.new
  		shopping_bag.user_id = current_user.id
  		shopping_bag.address_line_id = params[:shopping_bag][:address_line_id]
  		shopping_bag.save
  		shopping_cart = current_user.shopping_cart
  		cart_items = current_user.shopping_cart.cart_items
  		shopping_cart.cart_items.each do |cart_item|
	  		bag_item = BagItem.new
	  		bag_item.id = cart_item.id
	  		bag_item.shopping_bag_id = shopping_bag.id
	  		bag_item.cd_product_id = cart_item.cd_product_id
	  		bag_item.delivery_status_id = 1
	  		bag_item.quantity = cart_item.quantity
	  		bag_item.purchase_price = cart_item.cd_product.price
	  		delete_flag = false
	  		bag_item.save
	  		cart_item.destroy
	  	end
  	end

  	private
  	def complete_params
  		params.require(:cart_item).permit(:cd_product_id, :quantity, :shopping_cart_id)
  		params.require(:address_line).permit(:id, :user_id, :name, :postcode, :prefecture_id, :city, :address)
  	end
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/complete.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="cart.css">
	<title>完了画面</title>
</head>
<body>
	<div class="container">
      	<div class="row">
			<h1>購入しました</h1>
			<%= link_to "トップページへ戻る" , cd_products_path %>
		</div>
	</div>

</body>
</html>

app/views/shopping_carts/purchase.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="cart.css">
	<title>確認画面</title>
</head>
<body>
	<div class="container">
      	<div class="row">
			<h1>確認画面</h1>

			<div class="cart_button">
				<%= link_to "ショッピングを続ける", cd_products_path %>
			</div>
			<table class="table table-striped">
				<tr>
					<th></th>
					<th>商品名</th>
					<th>価格</th>
					<th>購入数</th>
					<th>合計</th>
				</tr>
				<% @cart_items.each do |cart_item| %>
					<tr>
						<td></td>
					    <td><%= cart_item.cd_product.name %></td>
					    <td><%= cart_item.cd_product.price %>円</td>
			    		<td><%= cart_item.quantity %></td>
					   	<td><%= (cart_item.cd_product.price).to_i * cart_item.quantity %></td>
					</tr>
				<% end %>
			</table>
			<div class="sum_price">
				<% %>
				<h3>合計：<%= (@shopping_cart.sum_total_price).to_i %>円</h3>
			</div>
			
			<div class="address_lines">
				<h2>お届け先</h2>
				<table class="table table-striped">
					<tr>
						<th></th>
						<th>購入者</th>
						<th>郵便番号</th>
						<th>都道府県</th>
						<th>市町村</th>
						<th>以下住所</th>
						<th>宛先氏名</th>
					</tr>
					<tr>
						<td></td>
						<td><%= @address_line.user.first_name %><%= @address_line.user.last_name %></td>
					    <td><%= @address_line.postcode %></td>
					    <td><%= @address_line.prefecture_id%></td>
					    <td><%= @address_line.city %></td>
					    <td><%= @address_line.address %></td>
					    <td><%= @address_line.name %></td>
					</tr>
				</table>
			</div>
			<%= form_for(ShoppingBag.new, url: complete_path) do |f| %>
				<%= f.hidden_field :address_line_id, value: @address_line_id %>
				<button><%= f.submit "購入する" %></button>
			<% end %>
		</div>
	</div>
</body>
</html>

app/views/shopping_carts/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="cart.css">
	<title>カートの中身</title>
</head>
<body>
	<%= render partial: 'cd_products/header' %>
  <div class="main clearfix">
	<div class="main-content">
      	<div class="row">
			<h1>ショッピングカート</h1>

			<div class="cart_button">
				<%= link_to "ショッピングを続ける", cd_products_path %>
			</div>
			<table class="table table-striped">
				<tr>
					<th></th>
					<th>商品名</th>
					<th>価格</th>
					<th>購入数</th>
					<th></th>
					<th>合計</th>
					<th></th>
				</tr>
				<% @cart_items.each do |cart_item| %>
					<tr>
						<td></td>
					    <td><%= cart_item.cd_product.name %></td>
					    <td><%= cart_item.cd_product.price %>円</td>
					    <%= form_for(cart_item) do |f| %>
					    	<div class="field">
					    		<td><%= f.number_field :quantity, min: 1 %></td>
					    		<td><%= f.submit "購入数を変更する" %></td>
					    	</div>
					   	<%end%>
					   	<td><%= (cart_item.cd_product.price).to_i * cart_item.quantity %></td>
					    <td><%= link_to "カートから削除", cart_item_path(cart_item.id), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
					</tr>
				<% end %>
			</table>
			<div class="sum_price">
				<% %>
				<h3>合計：<%= (@shopping_cart.sum_total_price).to_i %>円</h3>
			</div>
			
			<div class="address_lines">
				<h2>お届け先</h2>
				<table class="table table-striped">
					<tr>
						<th></th>
						<th>購入者</th>
						<th>郵便番号</th>
						<th>都道府県</th>
						<th>市町村</th>
						<th>以下住所</th>
						<th>宛先氏名</th>
					</tr>
					<%= form_tag('/confirmation', :method => :get) do %>
						<% @address_lines.each do |address_line| %>
							<tr>
								<div class="field">
									<td><%= check_box 'address_line','address_line_id', {:checked => false}, address_line.id, false %></td>
								</div>
								<td><%= address_line.user.first_name %><%= address_line.user.last_name %></td>
							    <td><%= address_line.postcode %></td>
							    <td><%= address_line.prefecture_id%></td>
							    <td><%= address_line.city %></td>
							    <td><%= address_line.address %></td>
							    <td><%= address_line.name %></td>
							</tr>
						<%end%>
						<%= submit_tag "確認画面へ進む" %>
					<%end%>
				</table>
				<button><%= link_to "届け先住所を変更する", address_lines_path(current_user) %></button>
			</div>
		</div>
	</div>
  </div>
  <%= render partial: 'cd_products/footer' %>

</body>
</html>