config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'cd_products#index'
  get '/guide' => 'users#guide'
 namespace :admin do
    resources :commodities, :only =>[:new,:create,:index,:edite,:update,:destroy]
    resources :companeys, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :doramas, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :movies, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :companeys, :only =>[:new,:create,:edit,:update,:destroy]
    resources :companeys, :only =>[:edit,:update]
    resources :users, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :artists, :only =>[:new,:create,:index,:edit,:update,:destroy]
  end
   get '/trend' =>'cms#trend'
 resources :cms, :only => [:index,:search]
  get '/era_search' => 'cd_products#era_search'
  get '/release_era_tag/:id' => 'release_era_tags#show', as: 'release_era_tag'
  get '/cd_products/:id' => 'cd_products#show'
  get '/search/list' => 'cd_products#list', as: :search_list
  get '/doramas/title_search/:id/:dorama_name' => "doramas#title_search", as: :dorama_title_search
  get '/doramas/feature' => 'doramas#feature', as: 'doramas_feature'
  get '/movies/title_search/:id/:movie_name' => "movies#title_search", as: :movie_title_search
  get '/movies/feature' => "movies#feature", as: :movie_feature
  get '/cms/commodity_search' => "cms#commodity_search", as: :cm_commodity_search
  get '/cms/company_search' => "cms#company_search", as: :cm_company_search
  get '/cd_products/search/artists_search_form' => "cd_products#artists_search_form", as: :artists_search_form
  get '/cd_products/search/songs_search_form' => "cd_products#songs_search_form", as: :songs_search_form
  get '/cd_products/search/artists_search' => "cd_products#artists_search", as: :artists_search
  get '/cd_products/search/songs_search' => "cd_products#songs_search", as: :songs_search
  resources :cd_products do
    post 'add' => 'favorites#create'
    delete '/add' => 'favorites#destroy'
  end
  resources :cd_products, :only =>[:index,:show,:era_search,:era_search_list,:search,:list]
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    password: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  devise_scope :user do
 post 'users/sign_up/confirm' => 'users/registrations#confirm'
 post 'users/sign_up/complete' => 'users/registrations#complete'
end

  resources :commodities, :only =>[:new,:create,:index,:edite,:update,:destroy]
  resources :companeys, :only =>[:new,:create,:index,:edit,:update,:destroy]
  resources :doramas, :only => [:new,:create,:index,:edit,:update,:destroy]
  resources :movies, :only =>[:new,:create,:index,:edit,:update,:destroy]
  resources :admins
  resources :bag_items, :only =>[:index,:edit,:update,:destroy]
  resources :shopping_bags, :only =>[:new,:create,:index,:show,:destroy]
  resources :cart_items, :only =>[:create,:destroy,:update]
  resources :shopping_carts, :only => [:new,:create,:index,:show,:destroy]
  get '/confirmation' => "shopping_carts#purchase"
  post  '/complete' => "shopping_carts#complete"
  resources :address_lines, :only =>[:new,:create,:index,:edit,:update,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/resignnation'
  get 'users/complete'
  resources :users,:except =>[:new,:create,:destroy]

end

app/models/cd_product.rb
class CdProduct < ApplicationRecord
	belongs_to :release_era_tag
	belongs_to :movie,optional: true
	belongs_to :dorama,optional: true
	belongs_to :commodity,optional: true
	belongs_to :artist
	belongs_to :label
	has_many :discs, dependent: :destroy, primary_key: "id", foreign_key: "cd_product_id"
	has_many :favorites, dependent: :destroy
	has_many :users,through: :favorites
	has_many :cart_items, dependent: :destroy
    enum sale_status_id: {
		準備中:1, 販売中:2
    }
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
	#adminページの画像挿入処理
	has_attached_file :jacket_image, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment :jacket_image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/admin/cd_products_controller.rb
class Admin::CdProductsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/cd_products_controller.rb
class CdProductsController < ApplicationController

include Search

  def index
    @cd_products = CdProduct.where(sale_status_id: 2).order(release_date: :desc).page(params[:page]).per(9)
    @movies = CdProduct.where("movie_id not ?", nil).where(sale_status_id: 2).order(release_date: :desc).limit(3)
    @commodities = CdProduct.where("commodity_id not ?", nil).where(sale_status_id: 2).order(release_date: :desc).limit(3)
    @doramas = CdProduct.where("dorama_id not ?", nil).where(sale_status_id: 2).order(release_date: :desc).limit(3)
    @user = current_user
  end

  def show
    @cd_product = CdProduct.find(params[:id])
    @discs = Disc.where(cd_product_id: (params[:id]))
    @songs = Song.where(disc_id: @discs.ids)
    @cds = CdProduct.where(artist_id: @cd_product.artist_id).where(sale_status_id: 2).page(params[:page]).per(4)

  end

  def era_search

  end

  def era_search_list
  end

  def artists_search_form

  end

  def artists_search
    search_name = params[:search_name]
    if search_name == ""
      return redirect_to artists_search_form_path
    end
    @artists = artists_name_search_function(search_name)
    @match_records = CdProduct.where(artist_id:@artists.ids).where(sale_status_id: 2).count
    @artists_cd_products = CdProduct.where(artist_id:@artists.ids).where(sale_status_id: 2).page(params[:page]).per(12)
    @path = controller_path + '#' + action_name
    def @path.is(*str)
        str.map{|s| self.include?(s)}.include?(true)
    end
    render template: "cd_products/list"
  end

  def songs_search_form

  end

  def songs_search
    search_name = params[:search_name]
    if search_name == ""
      return redirect_to songs_search_form_path
    end
    @cd_products = songs_name_search_function(search_name)
    @match_records = CdProduct.eager_load({:discs => :songs}).where("songs.name LIKE ?", "%" + search_name + "%").count
    @path = controller_path + '#' + action_name
    def @path.is(*str)
        str.map{|s| self.include?(s)}.include?(true)
    end
    render template: "cd_products/list"
  end

  def list

  end
end

app/helpers/admin/cd_products_helper.rb
module Admin::CdProductsHelper
end

app/helpers/cd_products_helper.rb
module CdProductsHelper
end

app/views/cd_products/_artists_search.html.erb
<%=form_tag(artists_search_path, method: :get) do %>
	<%= label_tag "アーティスト名検索" %>
	<%= text_field_tag :search_name %>
	<%= submit_tag "検索" %>
<% end %>

app/views/cd_products/_footer.html.erb
<div class="footer">
		<div class="footer-nav">
			<p>trend music encountについて</p>
			<ul class="footer-nav-list">
				<% if user_signed_in? %>
				<li class="footer-nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
				<% else %>
				<li class="footer-nav-item"><a href="/users/sign_in">ログイン</a></li>
				<% end %>
				<li class="footer-nav-item"><a href="/users/sign_up">新規登録</a></li>
				<li class="footer-nav-item"><a href="/guide">初めての方はこちら</a></li>
				<li class="footer-nav-item"><a href="/era_search">あの頃検索</a></li>
			</ul>
			<p>検索関連</p>
			<ul class="footer-nav-list">
				<li class="footer-nav-item"><a href="/cd_products/search/artists_search_form">アーティスト検索トップ</a></li>
				<li class="footer-nav-item"><a href="/cd_products/search/songs_search_form">曲名検索トップ</a></li>
			</ul>
			<p>映画関連</p>
			<ul class="footer-nav-list">
				<li class="footer-nav-item"><a href="/movies">映画関連トップ</a></li>
				<li class="footer-nav-item"><a href="/movies/feature">最新映画情報</a></li>
			</ul>
			<p>ＣＭ関連</p>
			<ul class="footer-nav-list">
				<li class="footer-nav-item"><a href="/cms">ＣＭ関連トップ</a></li>
				<li class="footer-nav-item"><a href="/trend">最新ＣＭ情報</a></li>
			</ul>
			<p>ドラマ関連</p>
			<ul class="footer-nav-list">
				<li class="footer-nav-item"><a href="/doramas">ドラマ関連トップ</a></li>
				<li class="footer-nav-item"><a href="/doramas/feature">最新ドラマ情報</a></li>
			</ul>
		</div>
		<p class="footer-text">TREND MUSIC ENCOUNT</p>
</div>

app/views/cd_products/_header.html.erb
<div class="header clear-fix" style = "margin-bottom: 10px">
		<h1 class="header-top">
			Trend Music Encount
		</h1>
		<nav>
			<ul class="nav-list">
				<li class="nav-list-item"><a href="/">HOME</a></li>
				<li class="nav-list-item"><a href="/movies">映画</a></li>
				<li class="nav-list-item"><a href="/cms">ＣＭ</a></li>
				<li class="nav-list-item"><a href="/doramas">ドラマ</a></li>
				<li class="nav-list-item"><a href="/cd_products/search/songs_search_form">曲検索</a></li>
				<li class="nav-list-item"><a href="/cd_products/search/artists_search_form">アーティスト検索</a></li>
				<% if user_signed_in? %>
                  <li class="nav-list-item"><%= link_to 'マイページ', user_path(current_user.id) %></a></li>
                <% end %>
			</ul>
		</nav>
		<div class="header-bottom">
			 <% if  user = current_user %>
				<button class="square_btn">
					<%=link_to "ショッピングカート", shopping_cart_path(current_user.shopping_cart.id) %>
				</button>
			<% else %>
				<div class="balloonoya square_btn" onclick="showBalloon()">ショッピングカート
					<span class="balloon1" id="makeImg">ログインすると閲覧できます</span>
				</div>
			<%end%>
		</div>
</div>

app/views/cd_products/_sidebar.html.erb
<div class="sidebar">
			<% if user_signed_in? %>
				<button class="side-columns"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></button>
			<%else%>
				<button class="side-columns"><a href="/users/sign_in">ログイン</a></button>
			<%end%>

			<button class="side-columns"><a href="/users/sign_up">新規登録</a></button>
			<button class="side-columns"><a href="/guide">初めての方はこちら</a></button>
			<button class="side-columns"><a href="/era_search">あの頃検索</a></button>
</div>

app/views/cd_products/_songs_search.html.erb
<%=form_tag(songs_search_path, method: :get) do %>
	<%= label_tag "曲名検索" %>
	<%= text_field_tag :search_name %>
	<%= submit_tag "検索" %>
<% end %>

app/views/cd_products/artists_search_form.html.erb
<%= render partial: 'cd_products/header' %>
  <div class="main clearfix">
	<div class="main-content">
	<%= render partial: 'cd_products/artists_search' %>
	</div>
	<%= render partial: 'cd_products/sidebar' %>
  </div>
  <%= render partial: 'cd_products/footer' %>

app/views/cd_products/era_search.html.erb
<html>
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="style.css">
	<style>
		.era_search_btn {
		  width: 320px;
		  height: 150px;
		  font-size: 50px;
		  line-height: 130px;
		}
		.era_search_table {
		  margin: auto;
		}
		.era_search_td {
          padding: 15px;
		}
        .era_search_title {
        	text-align: center;
        	font-size: 20px;
        	font-weight: 500;
        }
	</style>
</head>
<body>
	<%= render partial: 'cd_products/header' %>
  <div class="main clearfix">
	<div class="main-content">
		<table class="era_search_table">
		  <thead>
		    <div class="well well-sm era_search_title clearfix"><span class="glyphicon glyphicon-headphones"></span> 楽曲の年代を選択</div>
		  </thead>
		  <tbody>
			<tr>
		      <td class="era_search_td"><%= link_to "1980年代", 'release_era_tag/1', class:"btn btn-lg btn-info era_search_btn glyphicon glyphicon-zoom-in" %></td>
			  <td class="era_search_td"><%= link_to "1990年代", 'release_era_tag/2', class:"btn btn-lg btn-info era_search_btn glyphicon glyphicon-zoom-in" %></td>
			</tr>
			<tr>
			  <td class="era_search_td"><%= link_to "2000年代", 'release_era_tag/3', class:"btn btn-lg btn-info era_search_btn glyphicon glyphicon-zoom-in" %></td>
			  <td class="era_search_td"><%= link_to "2010年代", 'release_era_tag/4', class:"btn btn-lg btn-info era_search_btn glyphicon glyphicon-zoom-in" %></td>

			</tr>
		  </tbody>
		</table>
	</div>
    <%= render partial: 'cd_products/sidebar' %>
  </div>
  <%= render partial: 'cd_products/footer' %>
</body>
</html>

app/views/cd_products/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="skippr.css">
	<link rel="stylesheet" href="style.css">
	<title>trend_music_encount</title>
</head>
<body>
	<%= render partial: 'cd_products/header' %>
  <% if  user = current_user %>
        <p>ようこそ<%= @user.first_name %>様</p>
    <%else%>
        <p>ようこそゲスト様</p>
  <%end%>

	<div class="main-visual">
        <div class="theTarget">
            <div class="slide_1" style ="background-image: url(/assets/main2.jpg);background-size: cover;"></div>
            <div class="slide_2" style ="background-image: url(/assets/movie_slider.jpg);background-position: left center;"></div>
            <div class="slide_3" style ="background-image: url(/assets/comodity_slider.jpg);background-position: left top;"></div>
            <div class="slide_4" style ="background-image: url(/assets/dorama_slider.jpg);background-position: left center;"></div>
            <div class="slide_5" style ="background-image: url(/assets/era_search.jpg);background-position: left top;"></div>
        </div>
	</div>
	<div class="main clearfix">
		<div class="main-content">
    <h3>CD一覧</h3>
      <% if@cd_products.present? %>
        <% @cd_products.each_with_index do |cd_product, i| %>
          <div class="col-xs-4">
            <% if cd_product.jacket_image.present? %>
              <%= link_to cd_product_path(cd_product.id) do %>
                <%= image_tag "#{cd_product.jacket_image}", :size =>'250x250' %>
              <% end %>
            <% else %>
              <%= link_to cd_product_path(cd_product.id) do %>
                <img src="/assets/no_image.jpg", width="250", height="250">
              <% end %>
            <% end %>
            <p>CD名：<%= cd_product.name %></p>
            <p>アーティスト名：<%= cd_product.artist.name %></p>
            <p>リリース日：<%= cd_product.release_date %></p>
          </div>
        <% end %>
      <% end %>
      <div class="col-xs-12"><%= paginate @cd_products %></div class="col-xs-12">
      <div class="col-xs-12"><h3>映画・CM・ドラマ関連CD</h3></div>
			<!-- 映画コンテンツ -->
			<div class="movie-content col-xs-12">
			  <% if @movies.present? %>
                <table class="table table-bordered">
                  <tbody>
                      <tr>
                          <% @movies.each_with_index do |cd_product, i| %>
                              <% if  i % 3 ==0 %>
                                    <tr>
                              <% end %>
                              <td><% if cd_product.jacket_image.present? %>
                                     <%= link_to cd_product_path(cd_product.id) do %>
                                       <%= image_tag "#{cd_product.jacket_image}", :size =>'250x250' %>
                                     <% end %>
                                   <% else %>
                                     <%= link_to cd_product_path(cd_product.id) do %>
                                       <img src="/assets/no_image.jpg", width="250", height="250">
                                     <% end %>
                                   <% end %>
                                  <p>CD名:<%= cd_product.name %></p>
                                  <p>映画名:<%= cd_product.movie.movie_name %></p>
                              </td>
                              <% if (i + 1) % 3 == 0 %>
                                    </tr>
                              <% end %>
                              <% if (i == @movies.size - 1) && ((i + 1) % 3 == 2)%>
                                  </tr>
                              <% end %>
                          <% end %>
                  </tbody>
                </table>
              <% end %>
			  <%= link_to "もっと見る",movies_path %>
			</div>

            <!-- CMコンテンツ -->
			<div class="cm-content col-xs-12">
			   <% if @commodities.present? %>
                <table class="table table-bordered">
                  <tbody>
                      <tr>
                          <% @commodities.each_with_index do |cd_product, i| %>
                              <% if  i % 3 ==0 %>
                                    <tr>
                              <% end %>
                              <td>
                                <% if cd_product.jacket_image.present? %>
                                  <%= link_to cd_product_path(cd_product.id) do %>
                                    <%= image_tag "#{cd_product.jacket_image}", :size =>'250x250' %>
                                  <% end %>
                                <% else %>
                                  <%= link_to cd_product_path(cd_product.id) do %>
                                    <img src="/assets/no_image.jpg", width="250", height="250">
                                  <% end %>
                                <% end %>
                                <p>CD名：<%= cd_product.name %></p>
                                <p>商品:<%= cd_product.commodity.commodity %></p>
                              </td>
                              <% if (i + 1) % 3 == 0 %>
                                    </tr>
                              <% end %>
                              <% if (i == @commodities.size - 1) && ((i + 1) % 3 == 2)%>
                                  </tr>
                              <% end %>
                          <% end %>
                  </tbody>
                </table>
              <% end %>
			  <%= link_to "もっと見る",cms_path %>
			</div>
			<!-- ドラマコンテンツ -->
			<div class="dorama-content col-xs-12">
			  <% if @doramas.present? %>
                <table class="table table-bordered">
                  <tbody>
                      <tr>
                          <% @doramas.each_with_index do |cd_product, i| %>
                              <% if  i % 3 ==0 %>
                                    <tr>
                              <% end %>
                              <td>
                                <% if cd_product.jacket_image.present? %>
                                  <%= link_to cd_product_path(cd_product.id) do %>
                                    <%= image_tag "#{cd_product.jacket_image}", :size =>'250x250' %>
                                  <% end %>
                                <% else %>
                                  <%= link_to cd_product_path(cd_product.id) do %>
                                    <img src="/assets/no_image.jpg", width="250", height="250">
                                  <% end %>
                                <% end %>
                                  <p>CD名：<%= cd_product.name %></p>
                                  <p>ドラマ:<%= cd_product.dorama.name %></p>
                              </td>
                              <% if (i + 1) % 3 == 0 %>
                                    </tr>
                              <% end %>
                              <% if (i == @doramas.size - 1) && ((i + 1) % 3 == 2)%>
                                  </tr>
                              <% end %>
                          <% end %>
                  </tbody>
                </table>
              <% end %>
			  <%= link_to "もっと見る",doramas_path %>
			</div>
		</div>
		<%= render partial: 'cd_products/sidebar' %>
	</div>
		<%= render partial: 'cd_products/footer' %>

	<script src="jquery-3.3.1.min.js"></script>
	<script src="skippr.min.js"></script>
	<script src="script.js"></script>
	<script>
		function showBalloon(){
			var wObjballoon	= document.getElementById("makeImg");
			if (wObjballoon.className == "balloon1"){
				wObjballoon.className = "balloon";
			}else{
				wObjballoon.className = "balloon1";
			}
		}
	</script>
</body>
</html>

app/views/cd_products/search.html.erb
<h1>CdProducts#search</h1>
<p>Find me in app/views/cd_products/search.html.erb</p>

app/views/cd_products/show.html.erb
<html>
  <head>
    <style>
    .cd_position {
      padding-right: 10px;
    }
    </style>
  </head>
  <body>
<!-- CD詳細 -->
  <%= render partial: 'cd_products/header' %>
  <div class="main clearfix">
    <div class="main-content">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-4">
              <% if @cd_product.jacket_image.present? %>
                        <%= image_tag "#{@cd_product.jacket_image}", :size =>'300x300' %>
                    <% else %>
                        <img src="/assets/no_image.jpg", width="300", height="300">
                    <% end %>
            </div>
            <div class="col-md-6">
              <table class="table table-striped">
                  <thead>
                  <tr>
                    <h4>CD情報</h4>
                  </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>タイトル</td>
                      <td><p><%= @cd_product.name %><p></td>
                      <td></td>
                    </tr>
                    <tr>
                      <td>アーティスト</td>
                      <td><%= @cd_product.artist.name %></td>
                      <td></td>
                    </tr>
                    <tr>
                      <td>価格（税込）</td>
                      <td>￥<%= @cd_product.price %></td>
                      <td><% if @cd_product.stock_number == 0 then %>SOLDOUT
                          <% else %>
                          <% @cd_product.stock_number >= 1  %>在庫あり
                          <% end %>
                      </td>
                    </tr>
                </tbody>
              </table>
              <button type="button" class="btn btn-danger btn-lg"><%= link_to "カートに入れる", cart_items_path(cd_product_id: @cd_product.id), method: :post %></button>

    <!-- ==================form_for での描き方 ====================== -->
    <!--
              <%#= form_for(CartItem.new) do |f| %>
                <%#= f.hidden_field :cd_product_id, value: @cd_product.id %>
                <button type="button" class="btn btn-danger btn-lg"><%#= f.submit "カートに入れる" %></button>
              <%# end %>
     -->
     <!-- ==============================end=============================== -->

            <% if user_signed_in? %>
              <button type="button" class="btn btn-warning btn-lg">
               <% if !Favorite.exists?(user_id:current_user.id,cd_product_id:@cd_product.id) %>
                <%= link_to "お気に入り",cd_product_add_path(@cd_product),method: :post %>
                <% else %>
                <%= link_to "お気に入り解除",cd_product_add_path(@cd_product),method: :delete %>
                <% end %>
                </button>
            <% else %>
            <button type="button" class="btn btn-warning btn-lg">お気に入り</button>
            <% end %>

              <table class="table table-bordered">
                  <thead>
                 <tr>
                  <h4>商品情報</h4>
                  </tr>
                </thead>
                  <tbody>
                    <tr>
                      <td>発売日</td>
                      <td><%= @cd_product.release_date %></td>
                    </tr>
                    <tr>
                      <td>レーベル</td>
                      <td><%= @cd_product.label.name %></td>
                    </tr>
                  </tbody>
              </table>
              </div>
            <div class="col-md-1"></div>
        </div>



        <h4>収録曲</h4>
          <% @discs.each do |disc| %>
            <table class="table table-hover">
                    <thead>
                      <tr>
                      <p>Disc<%= disc.disc %></p>
                      </tr>
                    </thead>
                    <tbody>
                      <% @songs.each do |song| %>
                        <% if song.disc_id == disc.id %>
                          <tr>
                            <td><%= song.track_number_id %></td>
                            <td><%= song.name %></td>
                            <td>
                              <% selected_genre = Genre.find_by(id: song.genre_id) %>
                              <%= selected_genre.name %>
                            </td>
                          </tr>
                        <% else %>
                        <% end %>
                      <% end %>
                    </tbody>
                  </table>
             <% end %>
        <!-- CD詳細ここまで -->

        <!-- 映画、ドラマ、CM情報 -->
                  <div class="well well-sm">アーティスト関連情報</div>
                      <div class="row">
                        <div class="col-md-4">
                          <% if  @cd_product.movie.present? %>
                          <%= image_tag "#{@cd_product.movie.movie_image}", :size =>'250x250' %>
                          <% else %>
                          <% end %>

                          <% if  @cd_product.dorama.present? %>
                          <%= image_tag "#{@cd_product.dorama.dorama_image}", :size =>'250x250' %>
                          <% else %>
                          <% end %>

                          <% if  @cd_product.commodity.present? %>
                           <iframe width="300" height="180" src=<%= @cd_product.commodity.video_url %> frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
                            </iframe>
                          <% end %>

                        </div>
                      <div class="col-md-8">
                        <table class="table">

                        <!-- 映画詳細-->
                        <% if  @cd_product.movie.present? %>
                          <thead>
                            <tr>
                              <th>
                                映画名:<%= @cd_product.movie.movie_name %>
                              </th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td>
                                映画公開日:<%= @cd_product.movie.movie_release %>
                              </td>
                            </tr>
                          </tbody>
                          <% else %>
                          <% end %>

                        <!-- ドラマ詳細-->
                          <% if  @cd_product.dorama.present? %>
                          <thead>
                            <tr>
                              <th>
                                ドラマ名ー<%= @cd_product.dorama.name %>
                              </th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td>放送開始日:<%= @cd_product.dorama.dorama_start_date %></td>
                            </tr>
                            <tr>
                              <td>放送曜日:<%= @cd_product.dorama.week_id %></td>
                            </tr>
                          </tbody>
                          <% else %>
                          <% end %>

    　　　　　　　　　　　　　<!-- CM詳細 -->
                          <% if  @cd_product.commodity.present? %>
                          <thead>
                            <tr>
                              <th>
                                商品名:<%= @cd_product.commodity.commodity %>
                              </th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td>
                                動画公開日:<%= @cd_product.commodity.upload_date %>
                              </td>
                            </tr>
                          </tbody>
                          <% else %>
                          <% end %>

                        </table>
                      </div>
                  </div>
        <!-- 映画、ドラマ、CM情報ここまで -->

        <!-- 関連楽曲 -->
                  <div class="well well-sm">このアーティストの関連楽曲</div>
                    <table>
                      <tbody>
                      <tr>
                        <% @cds.each do |cd_product| %>
                        <td class="cd_position">
                          <% if cd_product.jacket_image.present? %>
                            <%= link_to cd_product_path(cd_product.id) do %>
                              <%= image_tag "#{cd_product.jacket_image}", :size =>'250x250' %>
                            <% end %>
                          <% else %>
                            <%= link_to cd_product_path(cd_product.id) do %>
                              <img src="/assets/no_image.jpg", width="250", height="250">
                            <% end %>
                          <% end %>
                          <p><%= cd_product.name %></p>
                        </td>
                        <% end %>
                      </tr>
                      </tbody>
                    </table>
                    <%= paginate @cds %>
         <!-- 関連楽曲ここまで -->
            </div>
            <%= render partial: 'cd_products/sidebar' %>
          </div>
      </div>
    </div>
  <%= render partial: 'cd_products/footer' %>
</body>
</html>

app/views/cd_products/songs_search_form.html.erb
<%= render partial: 'cd_products/header' %>
  <div class="main clearfix">
	<div class="main-content">
		<%= render partial: 'cd_products/songs_search' %>
	</div>
	<%= render partial: 'cd_products/sidebar' %>
  </div>
  <%= render partial: 'cd_products/footer' %>