config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'cd_products#index'
  get '/guide' => 'users#guide'
 namespace :admin do
    resources :commodities, :only =>[:new,:create,:index,:edite,:update,:destroy]
    resources :companeys, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :doramas, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :movies, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :companeys, :only =>[:new,:create,:edit,:update,:destroy]
    resources :companeys, :only =>[:edit,:update]
    resources :users, :only =>[:new,:create,:index,:edit,:update,:destroy]
    resources :artists, :only =>[:new,:create,:index,:edit,:update,:destroy]
  end
   get '/trend' =>'cms#trend'
 resources :cms, :only => [:index,:search]
  get '/era_search' => 'cd_products#era_search'
  get '/release_era_tag/:id' => 'release_era_tags#show', as: 'release_era_tag'
  get '/cd_products/:id' => 'cd_products#show'
  get '/search/list' => 'cd_products#list', as: :search_list
  get '/doramas/title_search/:id/:dorama_name' => "doramas#title_search", as: :dorama_title_search
  get '/doramas/feature' => 'doramas#feature', as: 'doramas_feature'
  get '/movies/title_search/:id/:movie_name' => "movies#title_search", as: :movie_title_search
  get '/movies/feature' => "movies#feature", as: :movie_feature
  get '/cms/commodity_search' => "cms#commodity_search", as: :cm_commodity_search
  get '/cms/company_search' => "cms#company_search", as: :cm_company_search
  get '/cd_products/search/artists_search_form' => "cd_products#artists_search_form", as: :artists_search_form
  get '/cd_products/search/songs_search_form' => "cd_products#songs_search_form", as: :songs_search_form
  get '/cd_products/search/artists_search' => "cd_products#artists_search", as: :artists_search
  get '/cd_products/search/songs_search' => "cd_products#songs_search", as: :songs_search
  resources :cd_products do
    post 'add' => 'favorites#create'
    delete '/add' => 'favorites#destroy'
  end
  resources :cd_products, :only =>[:index,:show,:era_search,:era_search_list,:search,:list]
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    password: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  devise_scope :user do
 post 'users/sign_up/confirm' => 'users/registrations#confirm'
 post 'users/sign_up/complete' => 'users/registrations#complete'
end

  resources :commodities, :only =>[:new,:create,:index,:edite,:update,:destroy]
  resources :companeys, :only =>[:new,:create,:index,:edit,:update,:destroy]
  resources :doramas, :only => [:new,:create,:index,:edit,:update,:destroy]
  resources :movies, :only =>[:new,:create,:index,:edit,:update,:destroy]
  resources :admins
  resources :bag_items, :only =>[:index,:edit,:update,:destroy]
  resources :shopping_bags, :only =>[:new,:create,:index,:show,:destroy]
  resources :cart_items, :only =>[:create,:destroy,:update]
  resources :shopping_carts, :only => [:new,:create,:index,:show,:destroy]
  get '/confirmation' => "shopping_carts#purchase"
  post  '/complete' => "shopping_carts#complete"
  resources :address_lines, :only =>[:new,:create,:index,:edit,:update,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/resignnation'
  get 'users/complete'
  resources :users,:except =>[:new,:create,:destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :address_lines, dependent: :destroy
          has_many :favorites, dependent: :destroy
          has_many :cd_products, through: :favorites
          has_one :shopping_cart
          has_many :shopping_bags
          accepts_nested_attributes_for :address_lines
          # 親モデルとネストしたいときに必須
  def full_name
    self.first_name + self.last_name
  end
  def full_name_kana
    self.first_name_kana + self.last_name_kana
  end

  enum delete_flag: {
    ユーザー: false,
    退会ユーザー: true
  }
  scope :active, -> { find_by(delete_flag: false) }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/}
  validates :last_name_kana, format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/}
  validates :telephone, presence: true, format: {with: /\A[0-9]{1,4}-[0-9]{1,4}-[0-9]{1,4}\z/}
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
  end

  def edit
  end

  def update
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

# 追加アクション
before_action :create, only: [:complete]
  def confirm
    @user = User.new(sign_up_params)
    if @user.valid?
      render :action => 'confirm'
    else
     render :action => 'new'
    end
  end

  def complete
    render :action => 'complete'
  end
#追加アクションここまで


  # GET /resource/sign_up
   def new
    build_resource
    resource.address_lines.build
    yield resource if block_given?
    respond_with resource
   end

  # POST /resource
   def create
     super
     if user_signed_in?
      shopping_cart = ShoppingCart.new
      shopping_cart.user_id = current_user.id
      shopping_cart.save
     end
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    @user = User.find_by(email: (params[:user][:email]))
    if @user.delete_flag == "退会ユーザー"
        redirect_to root_path and return
    end
     super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, except: [:complete,:guide]
# @user.address_lines.build ←newのときは書いたほうがいい
  def guide
  end

  def show
    @user = User.find(current_user.id)
    @favorites = current_user.favorites
    @shopping_bags = current_user.shopping_bags
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
      @user = User.find(current_user.id)
      # @user.id = current_user.id
    @user.update(user_params)
    redirect_to @user
  end

  def resignnation
  end

  def complete
     @user = current_user
    if @user.update(delete_flag:true)
      session.destroy
    end
  end
end

private
  def user_params
      params.require(:user).permit(:first_name, :last_name, :first_name_kana,:last_name_kana, :email, :telephone, address_lines_attributes:[:id, :name, :postcode, :prefecture_id,:city,:address])
  end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/complete.html.erb
<h2>退会手続きが完了しました</h2>
<%= link_to"TOPへ戻る", root_path %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
    <%= render partial: 'cd_products/header' %>
  <div class="main clearfix">
    <div class="main-content">
        <div class="body">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-6">
                            <h1>プロフィール編集</h1>
                        <%= form_for(@user) do |f| %>
                            <div>
                                <label>ユーザーネーム</label>
                                <%= f.text_field :first_name ,placeholder: "苗字"  %>
                                <%= f.text_field :last_name ,placeholder: "名前" %>
                            </div>
                            <div>
                                <label>ユーザーネーム(カナ)</label>
                                <%= f.text_field :first_name_kana ,placeholder: "ミョウジ"  %>
                                <%= f.text_field :last_name_kana ,placeholder: "ナマエ" %>
                            </div>
                            <div>
                                <label>電話番号</label>
                                <%= f.text_field :telephone ,placeholder: "TEL"  %>
                            </div>
                            <div>
                                <label>メールアドレス</label>
                                <%= f.text_field :email , placeholder: "e-mail" %>
                            </div>
                            <%= f.fields_for :address_lines do |s| %><!-- 親のｆが必要 -->
                            <div>
                                <label>郵便番号</label>
                                <%= s.text_field :postcode ,placeholder: "○○○-○○○○"  %>
                            </div>
                            <%= render 'address_lines/form',s:s %>
                            <div>
                                <label>市・町・村</label>
                                <%= s.text_field :city ,placeholder: ""  %>
                            </div>
                            <div>
                                <label>建物名・番地</label>
                                <%= s.text_field :address ,placeholder: ""  %>
                            </div>
                        <% end %>
                         <%= f.submit "変更を保存", class:"btn" %>
                        <% end %>
                        </div>
                    </div>
                </div>
            </div>
        <p><%= link_to "退会についてはコチラ", users_resignnation_path %></p>
    </div>
  </div>
  <%= render partial: 'cd_products/footer' %>
</body>
</html>

 

app/views/users/guide.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="guide.css">
	<title>初めての方はこちら</title>
</head>
<body>
	  <%= render partial: 'cd_products/header' %>
  <div class="main clearfix">
    <div class="main-content">
		<div class="container">
			<div class="row">
				<h1>はじめてガイド</h1>
				<div class="guide1">
				<h2>trend_music_encountとは</h2>
					<div class="caption">
						<p>映画やドラマ、CMなどに使われた曲情報をメインとしたCDショップです。</p>
						<p>あの映画やドラマのエンディング、オープニングが知りたいけど曲名がわからない・・・</p>
						<p>CMで使われてるあの曲が知りたいけど、商品名や会社名しかわからない・・・</p>
						<p>そんなときはこのサイトから検索して見ましょう！曲検索から商品購入までサポート致します。</p>
					</div>
				</div>
				<div class="guide2">
					<h2>購入までの流れ</h2>
					<div class="sub">
						<h3>step1.欲しい楽曲を検索</h3>
						<div class="caption">
							<p>映画、ドラマ、CM(商品名、会社名)から曲を検索できます。曲名やアーティスト名がわからなくても大丈夫！</p>
							<p>テレビや映画で流れていた曲情報を素早くキャッチできます。</p>
						</div>
					</div>
					<div class="sub">
						<h3>step2.ショッピングカートに商品を追加</h3>
						<div class="caption">
							<p>曲が見つかったあと、そのまま購入したいときはショッピングカートへ追加してください。</p>
							<p>忙しくて時間がないときも、近くにCDショップがない時でもお買い求め頂けます！</p>
						</div>
					</div>
					<div class="sub">
						<h3>step3.購入ボタンをクリック！</h3>
						<div class="caption">
							<p>ショッピングが終わり、購入したいCDをカゴに入れたら、購入ボタンをクリック！</p>
							<p>商品の発送状況はマイページからご確認頂けます。</p>
						</div>
					</div>
				</div>
				<div class="guide3">
					<h2>ユーザーだけのおすすめ機能</h2>
					<div class="sub">
						<h3>お気に入り</h3>
						<div class="caption">
							<p>検索した曲情報をまとめておける機能です。</p>
							<p>画面にあるハートボタンをクリックし、色がつくとお気に入り登録完了！</p>
							<p>追加したものはマイページにあるお気に入りページからご確認することができます。</p>
						</div>
					</div>
				</div>
				<div class="guide4">
					<p>ユーザー専用機能は随時追加予定！</p>
					<p>登録はこちら</p>
					<p><%= link_to "新規登録", new_user_session_path %></p>
				</div>
			</div>
		</div>
	</div>
    <%= render partial: 'cd_products/sidebar' %>
  </div>
  <%= render partial: 'cd_products/footer' %>
</body>
</html>

app/views/users/resignnation.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<div class="col-xs-8">
				<div class="unsubscribe-wrapper">
					<h3>退会フォーム</h3>
					<div class="unsubscribe-head">
						<h3>退会について</h3>
					</div>
					<div class="unsubscribe-main">
						<h3>退会ボタンよりご退会よりご退会いただけます。 <br>退会されますと購入履歴の閲覧、お気に入りの閲覧及び当サイトでの各種検索機能の利用、商品の購入等がご利用できなくなります。 <br>予めご了承くだいさい。
						</h3>
					</div>
					<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#sampleModal">退会する</button>
					<!-- モーダル・ダイアログ -->
					<div class="modal fade" id="sampleModal" tabindex="-1">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
									<h4 class="modal-title">本当に退会してよろしいですか？</h4>
								</div>
								<div class="modal-body">
									<%= link_to"はい", users_complete_path, class: "btn btn-warning btn-lg" %>
								<h3 class="btn btn-primary btn-lg">いいえ</h3>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
								</div>
							</div>
						</div>
					</div>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="skippr.css">
	<link rel="stylesheet" href="style.css">
</head>
<body>
	<h1>マイページ</h1>
	<div class="body">
		<div class="profile container">
			<div class="row">
			<div class="col-xs-6">
					<div class=profile-box>
						<%= link_to "topページへ戻る", root_path %>
						<ul class="list-group">
							<% @user.address_lines.each do |addressline| %>
							<li class="list-group-item list-group-item-info" style="text-align: center"><strong>ユーザープロフィール</strong></li>
							<li class="list-group-item"><strong>ユーザーネーム</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= current_user.full_name %></li>
							<li class="list-group-item"><strong>ユーザーネーム(カナ)</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @user.full_name_kana %></li>
							<li class="list-group-item"><strong>メールアドレス</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <%= @user.email %></li>
							<li class="list-group-item"><strong>電話番号</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <%= @user.telephone %></li>
							<li class="list-group-item"><strong>郵便番号</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;〒<%= addressline.postcode %></li>
							<li class="list-group-item"><strong>都・道・府・県</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= addressline.prefecture_id %></li>
							<li class="list-group-item"><strong>区・市・町・村</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= addressline.city %></li>
							<li class="list-group-item"><strong>建物名・番地 </strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= addressline.address %></li>
							<% end %>
						</ul>
					</div>
					<div>
						<% if @user.id == current_user.id %>
		        		<p><%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-success " %></p>
		        		<% end %>
					</div>
					<div class="container">
						<div class="row">
							<h2>購入履歴</h2>
							<table class="table table-striped">
								<% @shopping_bags.each do |shopping_bag| %>
								<tr>
									<th>送付先</th>
									<th>購入者</th>
									<th>購入日</th>
									<th></th>

								</tr>
								<tr>
									<td>
										<%= shopping_bag.address_line.name %>様
										〒<%= shopping_bag.address_line.postcode %>
										<%= shopping_bag.address_line.prefecture_id %>
										<%= shopping_bag.address_line.city %>
										<%= shopping_bag.address_line.address %>
									</td>
									<td>
										<%= shopping_bag.user.first_name %><%= shopping_bag.user.last_name %>
									</td>
									<td><%= shopping_bag.created_at.strftime('%Y年%m月%d日') %></td>
								</tr>
								<tr>
									<th>商品情報</th>
									<th>購入枚数</th>
									<th>発送ステータス</th>
									<th>総計</th>
								</tr>
								
									<% shopping_bag.bag_items.each do |bag_item| %>
									<tr>
										<td>
											<%= bag_item.cd_product.name %>
											：<%= bag_item.purchase_price %>円

										</td>
										<td><%= bag_item.quantity %>点</td>
										<td><%= bag_item.delivery_status_id %></td>
									
									<%end%>
									<td><%= (shopping_bag.sum_total_price).to_i %>円</td>
								</tr>
								<%end%>
							</table>
						</div>
					</div>
					<div class="container">
						<ul class="list-group">
							<li  class="list-group-item list-group-item-info">お気に入り商品リスト</li>
						</ul>
							<div class="main-visual">
        						<div class="theTarget">
          							<% @favorites.each_with_index do |favorite,i| %>
          							<% if i % 4 == 0 %>
          								<div class="slide">
          							<% end %>
						                    <div class="col-xs-3">
						                      <% if favorite.cd_product.jacket_image.present? %>
						                      <%= link_to cd_product_path(favorite.cd_product.id) do %>
						                          <%= image_tag "#{favorite.cd_product.jacket_image}", :size =>'200x200' %>
						                          <% end %>
						                      <% else %>
						                        <%= link_to cd_product_path(favorite.cd_product.id) do %>
						                          <img src="/assets/no_image.jpg", width="250", height="250">
						                          <% end %>
						                      <% end %>
				    					        <p><strong>商品名：</strong><%=favorite.cd_product.name %></p>
												<p><strong>価格：</strong>￥<%=favorite.cd_product.price %>(税込み)</p>
												<p><strong>アーティスト名：</strong><%= favorite.cd_product.artist.name %></p>
												<p><strong>リリース日：</strong><%= favorite.cd_product.release_date %></p>
				    				        </div>
				    				 <% if (i + 1) % 4 == 0 %>
				    				 	</div>
				    				 <% end %>
				    				 <% if (i == @favorites.size - 1) && ((i + 1) % 4 != 0)%>
				    				 	</div>
				    				 <% end %>
				    				<% end %>
			           
        						</div>
							</div>
			</div>
		</div>
	</div>
	<script src="jquery-3.2.1.min.js"></script>
	<script src="skippr.min.js"></script>
	<script src="script.js"></script>
</html>